# Generated by Django 3.2.5 on 2021-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20210314_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('ART', 'Art'), ('PHOTO', 'Photo'), ('PROGRAMMING', 'Programming'), ('MISCALLENOUS', 'Miscallenous'), ('UPDATE', 'Update'), ('MOVIES', 'Movies'), ('JOKE', 'Joke')], default='MISCALLENOUS', max_length=23),
        ),
    ]
